openapi: 3.1.0
info:
  title: DERMIS - Skin Evaluation API
  description: API for DERMIS system which evaluates skin conditions
  version: 0.0.0
paths:
  /imgeval:
    post:
      requestBody:
        description: Contains data for skin evaluation
        content:
          image/jpeg:
            schema:
              type: string
              format: byte
              description: base64 encoded image
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema: # Need description somewhere
                type: array
                items:
                  type: object
                  properties:
                    condition:
                      type: string
                    confidence:
                      type: number
                    treatment:
                      type: string


