openapi: 3.0.3
info:
  title: DERMIS - Skin Evaluation API
  description: API for DERMIS System which evaluates skin conditions.
  version: 0.2.0
paths:
  /imgeval:
    post:
      summary: Evaluate skin condition based on the given image
      description: |
        Predict skin condition based on the image in request body with trained intelligent model.
        Returns possible condition and its confidence level.
      requestBody:
        description: Contains data used for prediction
        content:
          image/jpeg:
            schema:
              title: Skin Image
              description: a base64-encoded image of the skin which is to be evaluated
              type: string
              format: byte
        required: true
      responses:
        "200":
          description: Successful Skin Evaluation
          content:
            application/json:
              schema:
                title: Skin Evaluation Result
                description: Skin evaluation result containing possible condition and its confidence level in JSON format
                type: object
                required:
                  - condition
                  - confidence
                properties:
                  condition:
                    type: string
                  confidence:
                    type: number
              examples:
                acne:
                  summary: Acne
                  description: Evaluation of acne condition with high confidence.
                  value:
                    condition: Acne
                    confidence: 0.7
                birthmark:
                  summary: Birthmark
                  description: Evaluation of birthmark condition with low confidence.
                  value:
                    condition: Birthmark
                    confidence: 0.3
          # links: # to be added
